### A simple get request to the test endpoint. No need for login
GET {{url}}/auth/test/

### Create a new user - this one will only get a USER role by default
POST {{url}}/auth/register/

{
    "username": "usermkmk21",
    "password": "123456"
}

###
POST {{url}}/auth/login/

{
    "username": "usermkmk21",
    "password": "123456"
}

> {%
    client.global.set("jwt_token", response.body.token);
%}

###
GET {{url}}/protected/user_demo/
Accept: application/json
Authorization: Bearer {{jwt_token}}

###
GET {{url}}/protected/admin_demo/
Accept: application/json
Authorization: Bearer {{jwt_token}}

### Add admin role to user
POST {{url}}/auth/user/addrole/
Accept: application/json
Authorization: Bearer {{jwt_token}}

{
    "role": "ADMIN"
}

### Reset token
GET {{url}}/auth/test/

> {%
    client.global.set("jwt_token", null);
%}


